### ISSUE TITLE
Which state of Unitree A1 for realsense camera input data? 

### ISSUE THREAD

**Issue by kenloumixx** [Road-Balance/rb_unitree_legged_sdk#2]
Hello, 

I am using Unitree A1, and I am aware that this repo is not related to the realsense camera but thank you for sharing this repo. 

Can I ask how you succeeded to use the camera input data from realsense depth camera? 

I am now struggling to get image data from realsense depth camera, and I'd like to figure out which state (ex. normal, sports mode of A1) the depth camera usb is recognized without the error of `RS2_USB_STATUS_BUSY`. 

The error now I am facing is 
```
unitree@nx:~$ rs-enumerate-devices
 08/06 15:53:16,318 ERROR [547821797696] (handle-libusb.h:95) failed to claim usb interface: 0, error: RS2_USB_STATUS_BUSY
Could not create device - failed to set power state . Check SDK logs for details
```

Thank you for reading this unrelevant issue!

**Comment by kimsooyoung** [comment]
Seems like mobile phone Application or sort of things are already grasping realsense.

To make them pause, 
1. find process PID which using realsense resources
2. force quit them and type `rs-enumerate-devices` again

```bash
# search process PIDs
$ ps faux | grep point
$ ps faux | grep rs

# force quit them
kill -9 <PID-NUM>
```

Lastly, I'd like to recommend some great slack group that can helpful to you 
https://robotdogs.slack.com/join/shared_invite/zt-1fvixx89u-7T79~VxmDYdFSIoTnSagFQ#/shared-invite/email
Moreover, @MAVProxyUser <= you'll learn many stuffs from his github repos

**Comment by kenloumixx** [comment]
@kimsooyoung Thank you so much for letting me know how to solve this issue and slack group, github repo!! :) 
I'll search other useful information in the groups and repos! Thank you again 😃

**Comment by kenloumixx** [comment]
@kimsooyoung Sorry for bothering again, as hoping this is the last question in this repo.. I tried to figure out the problem and suddenly the Jetson got stuck into infinite loading mode, probably due to the lack of storage. So I decided to reflash the Jetson but my laptop didn't recognize 'NVidia Corp' when I run 'lsusb'. Therefore, I'd like to ask if you ever reflashed Jetson and if so, how did you do it? As the jetson is covered by robot, I think it is hard to open the robot and find the recovery button in Jetson.

**Comment by kimsooyoung** [comment]
> That's not bothering, Feel free to ask me any question.

Oh bro seems like your Jetson got damanged. I'll tell you how to factory reset your system. 

Sol 1. HW refresh
* Ask new SD card or New Jetson to Unitree.
* Disassemble body parts and unplug damaged SD card or damaged Jetson 

Sol 2. Attach additional computer
* As you said before, you have to access to Jetson for reset. But A1's Jetson uses custom dev kit so you can't.
* But you can still access to A1 system through Ethernet port. Attach your own PC with A1 and set Eth port to `192.168.123.162`
* Try unitree legged sdk from new machine

p.s. Nowadays I'm making my own quadruped gait controller with Go1.

**Comment by MAVProxyUser** [comment]
Unitree go1 Air, Pro, and MAX have had their inner MIT Cheetah released! No longer is there an artificial pay for play limitation on LOW-LEVEL access. The
encryptedCRC method has been bypassed, and now all go1 dogs can be treated equally. Please use this responsibly.

https://twitter.com/d0tslash/status/1667202160042422272

https://twitter.com/Bin4ryDigit/status/1667202114232172560

You should try to get your gait controller running on the hacked SDK. https://github.com/Bin4ry/free-dog-sdk
